FROM python:3.9

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    git clone https://github.com/theo923/PredatorHub-Python.git ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "run.py"]
