version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
