# Stage 1 - the build process
FROM node:16 as build-deps
WORKDIR /usr/src/app
RUN apt-get update && \
    apt-get install -y git && \
    git clone https://github.com/theo923/PredatorHub-React.git ./

RUN yarn install
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.19.0-alpine
COPY --from=build-deps /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
